[[shades]]
name = "blue-light-filter"
intensity = 1.0
start_time = 00:00:00
end_time = 08:00:00

[[shades]]
name = "color-filter"
[shades.config]
type = "protanopia" # "protanopia", "deuteranopia", "tritanopia"
intensity = 1.0     # 0.0 - 1.0
